name: lumohub
description: "Lumohub es un clon de Github pero con esteroides."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  image_picker: ^1.0.8
  firebase_storage: ^11.7.1
  cloud_firestore: ^4.16.1
  path_provider: ^2.1.3
  mime: ^1.0.5
  cached_network_image: ^3.3.1
  flutter_image: ^4.1.11
  http: ^1.2.1
  material_design_icons_flutter: ^7.0.7296
  firebase_app_check: ^0.2.2+1
  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

